### ISSUE TITLE
videos did not start in oldtube

### ISSUE THREAD

**Issue by yves01blava** [arielscarpinelli/oldtube#12]
I have just installed oldtube on my Samsung UE40EH5450. It seems that I can search videos in application, but none of them starts. TV screen remains black or sometimes there is one blue line at the bottom of screen.

Any idea how to fix it?

**Comment by pauletask8** [comment]
I have exactly the same issue, started +- 4 days ago. For months I used the app with no issues, maybe it is something with youtube.

**Comment by arielscarpinelli** [comment]
Yes, youtube changed its embedded player and cannot work with (some?) TVs anymore.

**Comment by arielscarpinelli** [comment]
From now on it will use its own player. This has flaws but for the moment is the only solution

**Comment by yslee0314** [comment]
Hi i'm still seeing this same issue on UA40ES5600. Not sure if this is resolved yet, may I know if the current app server IP is using which version deploy?
