### ISSUE TITLE
Search results should not be interactive

### ISSUE THREAD

**Issue by Redirts** [arielscarpinelli/oldtube#15]
I think searching would be faster if it only launched search results once we click "Enter" instead of the search being interactive (after a new letter is typed).

**Comment by slawkens** [comment]
Yeah this is pretty annoying. Apps freezes every time I type one letter. It takes 2-3 second or event more on slower connections to type one letter.

**Comment by engasm1989** [comment]
I second that

**Comment by arielscarpinelli** [comment]
OK. Just implemented this
