### ISSUE TITLE
Some videos don't play

### ISSUE THREAD

**Issue by Redirts** [arielscarpinelli/oldtube#2]
Hi,

Many videos do not play on oldtube since a message is displayed saying they can only be played by going to youtube.com page. I think this is due to restrictions from companies like Vevo, etc. that block playing from third-party apps.

I am able to play fine if I open the browser on my samsung and navigate to the youtube.com page.
Is there any solution to this problem?

Thanks

**Comment by arielscarpinelli** [comment]
Nope. The app embeds the video in an iframe. If the video is restricted for not playing on iframe there isn't something we could do (without trying to use some kind of "youtube downloader" hack, i.e. out of API terms).

And the Search APIs don't let you to filter those out at least to avoid the bad experience ¯\_(ツ)_/¯
