### ISSUE TITLE
Error: Daily Limit Exceeded

### ISSUE THREAD

**Issue by seffs** [arielscarpinelli/oldtube#26]
Just installed the app. The API has hit the limit. Is it possible to put my own API Google key?

Thanks

**Comment by Mynacol** [comment]
A more permanent solution would be the abandonment of the official APIs.
Related projects to the already used ytdl can be used as alternative:
- [ytsr](https://github.com/TimeForANinja/node-ytsr) to search for videos/channels
- [ytpl](https://github.com/TimeForANinja/node-ytpl) to get information about playlist and cannels

The login into YouTube accounts is not easily replaceable. But the other changes would get the count of API calls down and at least some functionality is still available if the quota is exceeded.
