### ISSUE TITLE
Error watching a video

### ISSUE THREAD

**Issue by CaioCesar657** [arielscarpinelli/oldtube#29]
When I start a video I get 
Error: ytdl
Error:{"line":32,"sourceId":1536442296,"sourceURL":"http://oldtube.us/app/index.js"}

**Comment by CaioCesar657** [comment]
![15963855851948996635755376102499](https://user-images.githubusercontent.com/63740166/89127442-d4ac6300-d4c3-11ea-9352-38180d964d2c.jpg)

**Comment by Mynacol** [comment]
With the update of ytdl the error should be fixed
