### ISSUE TITLE
SSL handshake failed in Emulator 4.5

### ISSUE THREAD

**Issue by gnanet** [arielscarpinelli/oldtube#5]
I tried both own built, and the one available over oldtube.us none of them started on my D5500, in the 4.5 TV Emulator with webinspector mode i see, which may be an indicator

iframe_api www.youtube.com | GET | (failed)SSL handshake failed
analytics.js www.google-analytics.com | GET | (failed)SSL handshake failed

**Comment by gnanet** [comment]
Made a test with the 2014 - 5.1 Emulator, it works flawless

**Comment by arielscarpinelli** [comment]
I had the exact same issue. I spent 3 days trying to update the root SSL certificates in the TV software without any luck. I've updated the Ubuntu VM ones but they seem to be ignored. I also mounted manually the the TV soft disk inside the VM and tried to find for them but couldn't.
