### ISSUE TITLE
Favorites tab gives error

### ISSUE THREAD

**Issue by Redirts** [arielscarpinelli/oldtube#7]
After login, when I login to my youtube account and navigate to the Favorites tab on Oldtube, I get a parsing error.

**Comment by arielscarpinelli** [comment]
And what does it say?

**Comment by Redirts** [comment]
"Failed to search for videos. Please try again. (Error: the playlist identified with the requests <code>playlistId</code> parameter cannot be found.)"

**Comment by arielscarpinelli** [comment]
Does this still happen?

**Comment by Redirts** [comment]
Not using the app anymore unfortunately.
