### ISSUE TITLE
Reducing text quantity on each video

### ISSUE THREAD

**Issue by Redirts** [arielscarpinelli/oldtube#9]
Hi,

Is it possible to truncate the text associated to each video on the search page?
Sometimes it's quite large and forces users unnecessary scrolling on the page. It also seems to slowdown the scrolling too.

Thanks

**Comment by arielscarpinelli** [comment]
The problem with cutting the text is that I should provide you an alternative to read the complete. For instance the Apple TV app makes a scrolling ticker when you have the item selected to let you see it all. There is not an equivalent for free in HTML. But I will check something up

**Comment by arielscarpinelli** [comment]
Just cut it to two lines
